<?php

$title = 'Create Account';
$this->headTitle($title);

$form->setAttribute('action', $this->url('accounts/add'));
$form->setAttribute('class', 'form-horizontal');
$form->prepare();
?>
<h1><?= $this->escapeHtml($title) ?></h1>

<?= $this->form()->openTag($form) ?>

<div class="form-group">
    <?= $this->formLabel($form->get('name')->setAttribute('class', 'form-control')) ?>
    <?= $this->formElement($form->get('name')) ?>
    <?= $this->formElementErrors($form->get('name'), ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($form->get('account_type')->setAttribute('class', 'form-control')) ?>
    <?= $this->formElement($form->get('account_type')) ?>
    <?= $this->formElementErrors($form->get('account_type'), ['class' => 'help-block']) ?>
</div>

<?= $this->formSubmit($form->get('submit')->setAttribute('class', 'btn btn-primary')) ?>
<?= $this->formHidden($form->get('account_id')) ?>
<?= $this->form()->closeTag() ?>